#+SETUPFILE:orgheader.org
#+TITLE:Økter i Fysikk 1

* uke 15
** Hjemmeprosjekt i påsken
*Kvelden før:*
- Sett en halvliter vann i kjøleskapet. Dagen etter vil dette vannet holde ca. 4 °C.
*Prosjektdagen:*
1. Finn fram en vannkoker (en kjele er også greit). Noter deg effekten til vannkokeren (typiske effekter er på rundt 2000 W). Dersom du bruker en kokeplate med kjele, må du slå opp kokeplatens effekt i bruksanvisningen eller søke på internett. Dette varierer fra plate til plate, men er gjerne på drøyt 1000 W.
2. Varmekapasiteten til vann er ca. 4,2 kJ/(kg K), altså tar det 4,2 kJ energi å varme opp én liter vann én grad celsius. Regn ut hvor lang tid det vil ta å varme halvliteren din med vann fra 4 °C til 100 °C.
3. Hell vannet vannkoker eller kjelen og skru på vannkokeren eller kokeplata (sett til maksimal effekt). Ta tiden det tar før vannet begynner å koke.
4. Hvordan stemmer punkt 2 overens med punkt 3?

Skriv ned målinger og utregninger, jeg ønsker å se disse etter påske.

** Skriftligvurdering i uke 18
*Uke 18* (Første hele uke etter påskeferien)

Skriftligvurdering i kapittel 9

Prøven blir på 90 minutter, og kommer til å ha en del 1 og en del 2. Del 1 er en flervalgsdel og noen enkle regneoppgaver («hva er totalmotstanden i kretsen?» osv.)  og gjennomføres uten hjelpemidler. I del 2 har dere tilgang på *kalkulator* samt *én a4-side* med selvskrevne notater.

*Forberedelsesoppgaver*
- Ugjorte oppgaver fra kapittelet (s. 286--291) Dersom antallet her er «mange», velg deg ut to oppgaver fra hvert delkapittel.

- 9.120, B-9.2, B-9.6, B-9.11, B-9.14

** Muntligvurdering i uke 21
I uke 21 setter jeg opp tjue-minutters muntligvurderinger med hver av dere. Samtalen er da knyttet til kapittel 10, samt ett selvvalgt område eller kapittel dere vil forbedre. Mangler du en tidligere vurdering, er det dette som blir satt til det selvvalgte området. Vanlig undervisning utgår denne uka.

* uke 12 :noexport:
** vurdering
* uke 11
** 9A Ladning
- Les gjennom 9A og svar på «Prøv deg»-oppgavene på side 263. *Svar skriftlig*
- Gjør oppgave 9.01--02 på side 286.
- Gjør oppgave 9.101--102 på side 377.

* uke 10 
** Fisjon
*Minimum*
7.20, 7.21, 7.22, 7.25, 7.28, 7.29, 7. 30

** Fusjon
*Minimum*
7.34, 7.35, 7.36

** Blandede oppgaver
Jobb med /Blandede oppgaver/ side 370.
* uke 9
** Kjernefysikk
- [[https://tabaa004.github.io/fysikk1/kjernefysikk.html][Presentasjon]]
** Atomkjernen
*Minimum*
7.02, 7.04

*Ytterligere*
7.102

** Krefter i en atomkjerne
*Minimum*
7.05, 7.07

*Ytterligere*
7.108, 7.109, 7.114

** Bevaringslover
*Bevaringslover*
7.09, 7.10, 7.11, 7.12, 7.14

* Uke 6
** Forberedelse til vurdering
Tirsdagens vurdering er som sagt prøve bestående av en del 1 og en del 2. Under del 1 har dere ingen hjelpemidler tilgjengelig, under del 2 kan dere ha med kalkulator eller PC (skal kun brukes som kalkulator) og /egenproduserte, håndskrevne notater/.

*Del 1 - Flervalgsdel*
Oppgaver à la:
Hvilken av påstandene under stemmer om dopplereffekten?
- Vi observerer høyere frekvens når en strålingskilde er på vei fra oss
- Vi observerer høyere frekvens når en strålingskilde er på vei mot oss
- Vi observerer høyere amplitude når en strålingskilde er på vei mot oss
- Vi observerer høyere amplitude når en strålingskilde er på vei fra oss

*Del 2 - Regnedel*
Jeg kommer til å legge vekt på at der viser at dere har forstått hva oppgaven ber om. Det vil si at også følgende er på plass:
- Utregninger med enheter og hensiktsmessig antall gjeldende siffer
- Figur
- Korte navn eller andre indikasjoner på hva dere bruker under utregningene (f.eks. «Kvantehypotesen» den første gangen du bruker $E = hf$).
- Korte, beskrivende svarsetninger.

Lykke til med forberedelsene!

** Oppgaver fra kapittel 5
| *minimum*     | 5.01, 06, 08, 10, 15, 18 (geogebra), 20, 21, 24, 27 |
| *ytterligere* | 5.32, 110, 117, 125, B-5.3,                         |

** Emisjon og absorpsjon
| *Minimum*     | 6.20, 22, 24, 27              |
| *Ytterligere* | 6.118, 124, 125, B-6.4, B-6.7 |
* Uke 5
** Atomets historie
| *Minimum*     | 6.05, 6.07 |
| *Ytterligere* |      6.101 |

** Kvantehypotesen
| *Minimum*     | 6.08, 6.09 |
| *Ytterligere* |      6.106 |

** Bohrs atommodell
| *Minimum*     | 6.11, 6.13 |
| *Ytterligere* |      6.109 |
